books/urls.py
from django.conf.urls import patterns, url
from books import views


urlpatterns = [
    url(r'^$', views.BooksModelView.as_view(), name = 'index'),
    
    url(r'^book/$', views.BookList.as_view(), name = 'book_list'),
    url(r'^author/$', views.AuthorList.as_view(), name = 'author_list'),
    url(r'^publisher/$', views.PublisherList.as_view(), name = 'publisher_list'),
    
    url(r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name = 'book_detail'),
    url(r'^author/(?P<pk>\d+)/$', views.AuthorDetail.as_view(), name = 'author_detail'),
    url(r'^publisher/(?P<pk>\d+)/$', views.PublisherDetail.as_view(), name = 'publisher_detail')

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^books/', include('books.urls', namespace = 'books'))
]

polls/urls.py
from django.conf.urls import url
from polls import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$',views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$',views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$',views.vote, name='vote')
]

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
	title = models.CharField(max_length = 100)
	authors = models.ManyToManyField('Author')
	publisher = models.ForeignKey('Publisher')
	publication_date = models.DateField()

	def __str__(self):
		return self.title

class Author(models.Model):
	salutation = models.CharField(max_length = 100)
	name = models.CharField(max_length = 50)
	email = models.EmailField()

	def __str__(self):
		return self.name

class Publisher(models.Model):
	name = models.CharField(max_length = 50)
	address = models.CharField(max_length = 100)
	website = models.URLField()

	def __str__(self):
		return self.name

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	"""docstring for Question"""
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question)		
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return self.choice_text

books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher

# Create your views here.

class BooksModelView(TemplateView):
	template_name = 'books/index.html'

	def get_context_data(self, **kwargs):
		context = super(BooksModelView, self).get_context_data(**kwargs)
		context['object_list'] = ['Book', 'Author', 'Publisher']
		return context

class BookList(ListView):
	model = Book

class AuthorList(ListView):
	model = Author

class PublisherList(ListView):
	model = Publisher


class BookDetail(DetailView):
	model = Book

class AuthorDetail(DetailView):
	model = Author

class PublisherDetail(DetailView):
	model = Publisher

mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
	template_name = 'home.html'
	def get_context_data(self, **kwargs):
		context = super(HomeView, self).get_context_data(**kwargs)
		context['object_list'] = ['polls','books']
		return context
	

polls/views.py
from django.shortcuts import render, get_object_or_404
from polls.models import Choice, Question
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
# Create your views here.


def index(request):
	latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
	context = {'latest_question_list':latest_question_list}
	return render(request,'polls/index.html',context)

def detail(request, question_id):
	question = get_object_or_404(Question, pk = question_id)
	context = {'question':question}
	return render(request, 'polls/detail.html', context)

def vote(request, question_id):
	p = get_object_or_404(Question, pk = question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html',{'question':p,'error_message':'You didn`t select a choice'})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))

def results(request, question_id):
	question = get_object_or_404(Question, pk = question_id)
	return render(request, 'polls/results.html',{'question':question})

books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
	<h1>{{ object.name }}</h1>
	<p>{{ object.salutation }}</p>
	<li>Email: {{ object.email }}</li>
{% endblock content %}

books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
	<h2>Author List</h2>
	<ul>
		{% for author in object_list %}
			<li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
		{% endfor %}
	</ul>
{% endblock content %}

books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
	<h1>{{ object.title }}</h1>
	<br>
	<li>
		Authors:
		{% for author in object.authors.all %}
			{{ author }}
			{% if not forloop.last %},{% else %}{%endif%}
		{% endfor%}
	</li>
	<li>Publisher: {{object.publisher}}</li>
	<li>Publication date: {{ object.publication_date }}</li>
{% endblock content %}

books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
	<h2>Book List</h2>
	<ul>
		{% for book in object_list %}
			<li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
		{% endfor %}
	</ul>
{% endblock content %}

books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
	<h2>Books Management System</h2>
	<ul>
		{% for modelname in object_list %}
			{% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
				<li><a href="{% url urlvar %}">{{ modelname }}</a></li>
			{% endwith %}
		{% endfor %}
	</ul>
{% endblock content %}

books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
	<h1>{{ object.name }}</h1>
	<p>{{ object.website }}</p>
	<li>Address: {{ object.address }}</li>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
	<h2>Publisher List</h2>
	<ul>
		{% for publisher in object_list %}
			<li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
		{% endfor %}
	</ul>
{% endblock content %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token%}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for={{ forloop.counter }}>{{ choice.choice_text }}</label></br>
	{% endfor %}
	<input type="submit" name="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li><a href="/polls/{{ question.id }}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in  question.choice_set.all %}
		<li>{{ choice.choice.text }} - {{ choice.votes }} vote{{choice.votes|pluralize}}</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}">
	<meta charset="utf-8">
	<title>{% block title %}My Amazing Site{% endblock %}</title>
</head>
<body>
	<div id="sidebar">
		{% block sidebar %}
			<ul>
				<li><a href="/">Project_Home</a></li>
				<li><a href="/admin">Admin</a></li>
			</ul>
		{% endblock%}
	</div>

	<div id="content">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Applicationi Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
	<li><a href="/books/"></a>Books_Home</li>
</ul>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
	<h2>Skim Django Application</h2>
	<ul>
		{% for appname in object_list %}
			{% with appname|add:":"|add:"index" as urlvar%}
				<li><a href="{% url urlvar %}">{{ appname }}</a></li>
			{% endwith %}
		{% endfor %}
	</ul>
{% endblock content %}